apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  MYSQL_USER: YXBwX2NsaWVudAo= # app_client
  MYSQL_PASSWORD: UGEyOTk3NXcwcmQK  # Pa$$w0rd
  MYSQL_HOST: bXlzcWwtMC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo= # mysql-0.mysql.svc.cluster.local
  MYSQL_DATABASE_NAME: dG9kb2FwcF9kYgo=  # todoapp_db