apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGEyOTk3NXcwcmQK  # Pa$$w0rd
  MYSQL_USER: YXBwX2NsaWVudAo= # app_client
  MYSQL_PASSWORD: UGEyOTk3NXcwcmQK  # Pa$$w0rd
  MYSQL_HOST: bXlzcWwtMC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo= # mysql-0.mysql.svc.cluster.local
  MYSQL_DATABASE_NAME: dG9kb2FwcF9kYgo=  # todoapp_db